### PR TITLE
Added Composer 2.0 API compatibility

### LINKED ISSUE #6: Composer V2 support
We are getting closer: https://github.com/composer/composer/milestone/23

### PR DESCRIPTION
**Pull request by tswestendorp**
Fixes #6

### CODE REVIEW

**Review by akondas — APPROVED** [review]
Looks ok for me, but we need to check it manually. From what I remember, some changes to api were required, but maybe something has changed :thinking:

**Comment by tswestendorp** [comment]
> Looks ok for me, but we need to check it manually. From what I remember, some changes to api were required, but maybe something has changed 🤔

You're right.. this wasn't enough, just tried to install the plugin with v2 and hitting some errors

**Comment by tswestendorp** [comment]
> You're right.. this wasn't enough, just tried to install the plugin with v2 and hitting some errors

Did some more work and testing.. I'm able to install using v1.10.10 and v2.0.6 now.. not sure yet if mirror replacement is working.

**Comment by akondas** [comment]
With this code mirror replacement is not working. Anyway, thank you for the work :beers:. Thanks to this, I was able to continue work in #9.

**Pull request closed without merging**
